// src/lib/notifications/types.js

export const NotificationType = {
  APPOINTMENT_CONFIRMED: "APPOINTMENT_CONFIRMED",
  APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
  APPOINTMENT_RESCHEDULED: "APPOINTMENT_RESCHEDULED",

  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  EARNING_PENDING: "EARNING_PENDING",

  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",

  REFUND_PROCESSED: "REFUND_PROCESSED",
  PAYOUT_COMPLETED: "PAYOUT_COMPLETED",
};
