import { Providers } from "@/src/providers/providers";
import Header from "@/src/components/Header/Header";
import { poppins } from "@/src/ui/font";
import "./globals.css";
import { AuthProvider } from "@/src/hooks/useAuth";
import { SessionProvider } from "next-auth/react";
import { Analytics } from "@vercel/analytics/next"

export const metadata = {
  title: "iPractis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Analytics>
        <SessionProvider>
          
        <AuthProvider>
        <Providers>
          <Header />

          <main>{children}</main>
        </Providers>
        </AuthProvider>
        </SessionProvider>
        </Analytics>
      </body>
    </html>
  );
}
