import { Providers } from "@/src/providers/providers";
import Header from "@/src/components/Header/Header";
import { poppins } from "@/src/ui/font";
import "./globals.css";

export const metadata = {
  title: "iPractis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Header />

        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
